name: test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install ruby python3-venv

    - name: clone leihs-instance
      run: git clone https://github.com/leihs/leihs-instance

    - name: initialize submodules
      working-directory: leihs-instance
      run: |
        git submodule update --init leihs
        cd leihs
        git submodule update --init --recursive

    - name: build hosts file
      working-directory: leihs-instance
      run: |
        echo '[leihs_server]' > hosts
        echo 'localhost   ansible_connection=local' >> hosts

    - name: build host vars
      working-directory: leihs-instance/host_vars
      run: |
        echo 'leihs_external_hostname: localhost' > localhost.yml
        echo 'ansible_host: localhost' >> localhost.yml
        echo 'leihs_send_mails: false' >> localhost.yml
        echo 'db_backup_keep_days: 4' >> localhost.yml
        echo 'db_backup_nigthly_enabled: false' >> localhost.yml
        echo 'db_backup_on_deploy: false' >> localhost.yml

    - name: update group vars
      working-directory: leihs-instance/group_vars
      run: |
        sed -i 's/force_redirect_to_https: yes$/force_redirect_to_https: false/' leihs_server.yml
        sed -i 's#ssl_certificate_file: .*$#ssl_certificate_file: /localhost.crt#' leihs_server.yml
        sed -i 's#ssl_certificate_key_file: .*$#ssl_certificate_key_file: /localhost.key#' leihs_server.yml
        cat leihs_server.yml

    - name: generate certificates
      run: >
        sudo openssl req -new -newkey rsa:4096 -x509 -sha256 -days 365 -nodes -out /localhost.crt -keyout /localhost.key -subj /CN=localhost/

    - name: deploy
      working-directory: leihs-instance
      run: sudo ./scripts/deploy

    - name: register admin
      run: |
        CSRF_TOKEN="$(curl -s 'https://verleih.virtuos.uni-osnabrueck.de/my/initial-admin' | sed -n 's/^.*csrf-token" value="\([^"]*\)".*$/\1/p')"
        curl -s 'https://verleih.virtuos.uni-osnabrueck.de/my/initial-admin' -H "x-csrf-token: ${CSRF_TOKEN}" -H "cookie: leihs-anti-csrf-token=${CSRF_TOKEN}" -F email=admin@lkiesow.io -F password=password -F csrf-token="${CSRF_TOKEN}"
