name: lint

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: set up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: install Python dependencies
      run: |
        pip install -r requirements.txt
        pip install bandit flake8 pyright yamllint

    - name: run flake8
      run: flake8 leihsldap

    - name: run bandit
      run: bandit -r leihsldap

    - name: run pyright
      run: pyright --skipunannotated leihsldap

    - name: run yamllint
      run: yamllint leihs-ldap.yml
